function diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)
Fig=figure('Name','Proiect CAG',...
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.8],...
           'NumberTitle','off','color',[0.75,0.75,0.75]);
            
T=1/F1;
t=0:T/100:N*T;
nt=length(t);
w1=2*pi*F1;
w2=2*pi*F2;


uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.5 0.03 0.2 .05],...
'String','BACK',...
'Callback','interface');




 %bushbutton for the document with formula
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.05 0.2 0.2 .05],...
'String','Ecuations',...
'Fontweight', 'bold',....
'FontSize', 12,...
'FontName', 'Arial',...
'Callback','formula');


%bushbutton for image
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.05 0.1 0.2 .05],...
'String','The schematic',...
'Fontweight', 'bold',....
'FontSize', 12,...
'FontName', 'Arial',...
'Callback','schematic2');

%bushbutton for image
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.05 0.03 0.2 .05],...
'String','Diff Amp',...
'Fontweight', 'bold',....
'FontSize', 12,...
'FontName', 'Arial',...
'Callback','schematic3');

ha = axes('units','normalized', ...
'position',[0 0 1 1]);
uistack(ha,'bottom');
I=imread('background32.jpg');
hi = imagesc(I);





uicontrol('Style','text','fontsize',13,... 
'Units','normalized',...
'Position',[0.135 0.88 0.05 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','A1(v)');
uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.135 0.84 0.05 .04],...
'String',A1,...
'backgroundcolor','w',...
'Callback',['A1=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);



uicontrol('Style','text','fontsize',13,... 
'Units','normalized',...
'Position',[0.190 0.88 0.05 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','A2(v)');

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.190 0.84 0.05 .04],...
'String',A2,...
'backgroundcolor','w',...
'Callback',['A2=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',16,... 
'Units','normalized',...
'Position',[0.245 0.88 0.08 .06],...
'backgroundcolor','k',...
'foregroundcolor','w',...
'string','F1(Hz)');

uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.245 0.84 0.08 .04],...
'backgroundcolor','w',...
'String',F1,...
'Callback',['F1=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',16,... 
'Units','normalized',...
'Position',[0.33 0.88 0.08 .06],...
'backgroundcolor','k',...
'foregroundcolor','w',...
'string','F2(Hz)');

uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.33 0.84 0.08 .04],...
'backgroundcolor','w',...
'String',F2,...
'Callback',['F2=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',19,... 
'Units','normalized',...
'Position',[0.1 0.62 0.05 .1],...
'backgroundcolor','k',...
'foregroundcolor','w',...
'string','Vi (v)');
    
uicontrol('Style','text','fontsize',19,... 
'Units','normalized',...
'Position',[0.1 0.37 0.05 .1],...
'backgroundcolor','k',...
'foregroundcolor','w',...
'string','Vo (v)');

uicontrol('Style','text','fontsize',19,... 
'Units','normalized',...
'Position',[0.415 0.88 0.08 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','N');

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.415 0.84 0.08 .04],...
'String',N,...
'backgroundcolor','w',...
'Callback',['N=','str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',18,... 
'Units','normalized',...
'Position',[0.9 0.74 0.09 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','VoH(v)');

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.9 0.7 0.09 .04],...
'String',Vo1,...
'backgroundcolor','w',...
'Callback',['Vo1=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',18,... 
'Units','normalized',...
'Position',[0.9 0.62 0.09 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','VoL(v)');

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.9 0.58 0.09 .04],...
'String',Vo2,...
'backgroundcolor','w',...
'Callback',['Vo2=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',13,... 
'Units','normalized',...
'Position',[0.9 0.5 0.09 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','R1(Ohmi)');

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.9 0.46 0.09 .04],...
'String',R1,...
'backgroundcolor','w',...
'Callback',['R1=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',13,... 
'Units','normalized',...
'Position',[0.9 0.38 0.09 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','R2(Ohmi)');

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.9 0.34 0.09 .04],...
'String',R2,...
'backgroundcolor','w',...
'Callback',['R2=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',13,... 
'Units','normalized',...
'Position',[0.9 0.14 0.09 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','R4(ohmi)');

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.9 0.1 0.09 .04],...
'String',R4,...
'backgroundcolor','w',...
'Callback',['R4=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);

uicontrol('Style','text','fontsize',13,... 
'Units','normalized',...
'Position',[0.9 0.26 0.09 .06],...
'foregroundcolor','w',...
'backgroundcolor','k',...
'string','R3(ohmi)');

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.9 0.22 0.09 .04],...
'String',R3,...
'backgroundcolor','w',...
'Callback',['R3=str2num(get(gco,''String'')),close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2)']);
    



uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.9 0.04 0.08 .05],...
'String','CLOSE',...
'Callback','close');

uicontrol('style','popup',...
    'units','normalized',...
    'position',[0.15 0.7 0.2 0.1],...
    'value',tip,...
    'string','Semnal Sinusoidal|Semnal Triunghiular|Semnal dinte de Fierastrau',...
    'callback','tip=get(gco,''value'');close;diferential(tip,R1,R2,R3,R4,A1,A2,F1,F2,N,Vo1,Vo2);');

%Meniuri
 menu = uimenu('Label', 'Bibliografie',...
                  'checked', 'on',...
                  'Foregroundcolor','b'); 


uimenu(menu, 'Label', 'Electronic amplifier',...
           'checked', 'on',...
           'Foregroundcolor', 'k',...
           'Separator', 'on',...
           'Callback', 'open(''Electronic amplifier.docx'')');


uimenu(menu, 'Label', 'Differential amplifier',...
           'checked', 'on',...
           'Foregroundcolor', 'k',...
           'Separator', 'on',...
           'Callback', 'open(''Differential amplifier.docx'')');


uimenu(menu, 'Label', 'Ecuations',...
           'checked', 'on',...
           'Foregroundcolor', 'k',...
           'Separator', 'on',...
           'Callback', 'open(''Ecuations.docx'')');

uimenu(menu, 'Label', 'Documentatie',...
           'checked', 'on',...
           'Foregroundcolor', 'k',...
           'Separator', 'on',...
           'Callback', 'open(''Documentatie.pdf'')');
       

       
% Meniul pentru iesire 
         uimenu(menu, 'Label', ' Close',...
           'checked', 'on',...
           'Foregroundcolor', 'k',...
           'Separator', 'on',...
           'Accelerator', 'Q',...
           'Callback', 'close;');
switch(tip)
    case 1
vi=A1*sin(2*pi*F1*t);
vi1=A2*cos(2*pi*F2*t);
    case 2
vi=(2*A1/pi)*asin(sin(w1.*t));
vi1=(2*A2/pi)*asin(cos(w2.*t));
    case 3
        vi=(2*A1/pi)*atan(tan(w1.*t./2));
        vi1=(2*A2/pi)*atan(tan(w2.*t./2));
end

h1=(R4./(R3+R4)).*(1+R2./R1) ;  
       h2=(R2./R1);
for k=1:nt;    
      vo(k)=h1.*vi(k)-h2.*vi1(k);
if vo(k)<Vo2;
    vo(k)=Vo2;
elseif vo(k)>Vo1;
    vo(k)=Vo1;
end
end
            
  axes('position',[0.2,0.55,0.65,0.19]);
plot(t,vi,'b',t,vi1,'r');
legend('Vi1','Vi2');
xlabel('Timpul (s)');
grid;
axes('position',[0.2,0.32,0.65,0.19]);
plot(t,vo);
legend('Vo');
xlabel('Timpul (s)');
hold on;
grid;

